Update README.md
kobotoolbox/form-builder-translations pull request #8
Opened 2021-03-10 20:13 UTC by JacquelineMorrissette

Updated the readme to include the most recent steps to update the djangojs.po file for translations.

2023-01-06 15:17 UTC, noliveleger requested changes

2023-01-06 15:17 UTC, noliveleger commented on README.md
> +* Once installed, move to the KPI root director and run `json2po jsapp/compiled/extracted-stings.json locale/en/LC_MESSAGES/djangojs.po`.
maybe `extracted-strings.json`?

2023-01-06 15:17 UTC, noliveleger commented on README.md
> +## Step 1: Convert Frontend Strings JSON to PO file
I've been told by our dear colleague that the adjective was `front-end`

2023-01-09 16:31 UTC, noliveleger approved these changes

2023-01-10 06:01 UTC, jnm approved these changes
Thanks; this is helpful, especially since we haven't used Poedit for so long. I hope we can simplify this more someday soon by automating some of the steps, e.g. the JSON to PO conversion. We started discussing that at https://chat.kobotoolbox.org/#narrow/stream/6-Support/topic/Approving.20new.20Language.20Translations.20on.20Transifex/near/20520

2023-01-10 06:01 UTC, merged